### ISSUE TITLE
Add documentation for typesafe slots

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/dev-site#84]

**Comment by meriouma** [comment]
Agreed. We are working hard to rewrite the whole GWTP section in the upcoming weeks

**Comment by olafleur** [comment]
@Chris-V Was that planned?

**Comment by jclariviere** [comment]
Already done ;)
https://github.com/ArcBees/dev-site/pull/102
https://github.com/ArcBees/dev-site/tree/develop-gwtp/site/src/main/markdown/gwtp_v2/core/slots

**Comment by olafleur** [comment]
Great, thanks! Closing, then.
