### ISSUE TITLE
Make documentation for Universal Analytics readable.

### ISSUE THREAD

**Issue by rdwallis** [ArcBees/dev-site#85]
All the docs for universal analytics are in master at: https://github.com/ArcBees/dev-site/tree/master/site/src/main/markdown/ua

But they don't show up at: http://dev.arcbees.com/

Can someone fix? I don't have time to learn how dev site works.

**Comment by christiangoudreau** [comment]
It's in our internal sprint. Should be done shortly :D

**Comment by rdwallis** [comment]
Cheers thanks
